### ISSUE TITLE
get_assets()

### ISSUE THREAD

**Issue by jesseves** [tamw-wnet/PBS_Media_Manager_Client#25]

**Comment by jesseves** [comment]
I'm trying to construct a query (similar to this one from the PBS docs) to get all full length assets belonging to a show:

`https://media.services.pbs.org/api/v1/assets/?show-id={show_id}&type=full_length`

But there doesn't seem to be a plain `get_assets()` function in the client.  Am I missing something?

**Comment by jesseves** [comment]
I'm trying to construct a query (similar to this one from the PBS docs) to get all full length assets belonging to a show:

`https://media.services.pbs.org/api/v1/assets/?show-id={show_id}&type=full_length`

But there doesn't seem to be a plain `get_assets()` function in the client.  Am I missing something?

**Comment by tamw-wnet** [comment]
I was under the (possibly incorrect) belief that requesting assets without referencing the direct parent wouldn't work.   So if you did 
https://media.services.pbs.org/api/v1/assets/?show-id={show_id}&type=full_length
it would return nothing, since 'full_length' assets have to be children of either an episode or a special.

If I'm wrong, we should make a method.  I think it would just be wrapper for 
get_list_data('/assets/', $queryargs)
and let people pass whatever filters they want in the query args.

**Comment by jesseves** [comment]
So, I think PBS must have added this after the initial release, because I had had a similar belief.  But, the query posted above works, and provides vastly different results than `https://media.services.pbs.org/api/v1/shows/{show_id}/assets/?type=full_length`.

For example, using Africa's Great Civilizations as an example, the assets endpoint returns the six full length episodes, while the shows endpoint returns nothing.

**Comment by tamw-wnet** [comment]
@jesseves if you code it up I'll accept the PR.

**Comment by jesseves** [comment]
Alrighty -- I'll give it a shot.

**Comment by tamw-wnet** [comment]
#26 looks great!  merged.  

If you get a chance sometime, please add a note to the README with how to use it etc.
