### ISSUE TITLE
Strict comparison in make_response_array() generates notices

### ISSUE THREAD

**Issue by jesseves** [tamw-wnet/PBS_Media_Manager_Client#37]
In `make_response_array()`, the client checks the HTTP response to see if data is returned using a strict comparison to `0`. 

However, when an asset doesn't exist, the API returns `false`, not `0`. This is generating undefined offset notices a few lines further down since the function continues to try to process the result even though no result exists.

Is there a reason for the strict comparison?  Switching from

`if (strpos($data[0], 'HTTP') === 0) {`

to 

`if (strpos($data[0], 'HTTP') == 0) {` 

clears things up for me.

**Comment by tamw-wnet** [comment]
@jesseves I've been seeing those offset notices in my logs too and meaning to do something about them.

The strict comparison thing is because of how strpos works -- strpos is actually returning "true" fundamentally if it finds HTTP at the 0th position in that line.    

We should keep the strpos === line as is, but I should do an earlier test in the code for the API returning false.

**Comment by jesseves** [comment]
I don't think that's quite right.  If I run `var_dump(strpos($data[0], 'HTTP'));` strpos isn't finding HTTP at all so is returning `false`, not `0`.  The response that's passed into the function just jumps right into the text "Not Found" without any sort of codes first.

> Not Found
> The requested URL /api/v1/assets/legacy/ was not found on this server.

**Comment by tamw-wnet** [comment]
that's the expected behavior of strpos -- in the case where we _do_ successfully find HTTP, it will return literal 0 because it will be at the beginning of the line, but in all other cases it will return false, which for == comparison is the same as 0.
`
$x=false;
if ($x==0) { echo "x is false"; }
if ($x===0) {echo "x is 0";}
`

That said, I'll put in an earlier test to get rid of the notices.

**Comment by tamw-wnet** [comment]
@jesseves see c8d156547beb370e2b7236a892c79a4f5e96a613 it solves the actual problem a little better.  The warning is being generated because in some case there's a response line that doesn't split on ": ".  In those cases the an array element was already being created with an element that was that line (but null value); now we test for the existence of the second array member.  the output should be identical, just no warning now.

**Comment by jesseves** [comment]
Is the whole of the response text really supposed to be the array key?

![screenshot-d7 weta org-2018 08 28-14-29-05](https://user-images.githubusercontent.com/19349103/44742824-d64aa080-aace-11e8-8fc4-5a40d89e3421.png)

**Comment by tamw-wnet** [comment]
It isn't ideal, it's just the least change from the current behavior.

**Comment by tamw-wnet** [comment]
that said, it's an easy tweak to not make it a key/value pair if there is no value.

**Comment by tamw-wnet** [comment]
I've been a little conflicted about what the best way to proceed is because generally the array that make_response_array() returns is usually associative, not indexed.   TL;DR  I forgot that if any elements of the array are parsable JSON I make the parsed json the []th element of tha returned array, so there's nothing sacred about the index vs associative thing.   So in this obnoxios 404 case we're getting the message will be the []th element of the array.   My updated commit is 19fad6b29e1feac21a5d6befcb10a06d415a8a90
